version: "3.6"

services:
  marketplace_frontend:
    image: marketplace_frontend:latest
    container_name: marketplace_frontend
    volumes:
      - ${FRONTEND}:/app
      - /app/node_modules
    networks:
      - marketplace-network
    restart: unless-stopped

  marketplace_db:
    image: postgres:11
    container_name: marketplace_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - marketplace-network
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data

  marketplace_backend:
    image: marketplace_backend:latest
    container_name: marketplace_backend
    build:
      context: .
      dockerfile: dockerfiles/app
    networks:
      - marketplace-network
    environment:
      - TZ=Europe/Moscow
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - SERVER_SALT=${SERVER_SALT}
      - SERVER_SECRET=${SERVER_SECRET}
      - EMAIL_LOGIN=${EMAIL_LOGIN}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SERVER=${EMAIL_SERVER}
      - EMAIL_ADDR=${EMAIL_ADDR}
    volumes:
      - ${BACKEND}:/app
    depends_on:
      - marketplace_db
    command: ./entrypoint.sh

  marketplace_nginx:
    image: nginx:latest
    container_name: marketplace_nginx
    volumes:
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
      - ${BACKEND}:/var/www/marketplace
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - marketplace_backend
    networks:
      - marketplace-network

  marketplace_redis:
    image: redis
    container_name: marketplace_redis
    networks:
      - marketplace-network
    expose:
      - "6379"

networks:
  marketplace-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}
